import { Category, MenuItem } from "@/types";

export const CATEGORIES: Category[] = [
    { id: '1', name: 'Popular', slug: 'popular' },
    { id: '2', name: 'Coffee', slug: 'coffee' },
    { id: '3', name: 'Snacks', slug: 'snacks' },
    { id: '4', name: 'Desserts', slug: 'desserts' },
    { id: '5', name: 'Drinks', slug: 'drinks' },
];

export const MENU_ITEMS: MenuItem[] = [
    // Coffee
    {
        id: '1',
        categoryId: '2',
        name: 'Cappuccino',
        description: 'Rich espresso with steamed milk foam.',
        price: 150,
        image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?q=80&w=600&auto=format&fit=crop',
        isPopular: true,
        isVeg: true,
    },
    {
        id: '2',
        categoryId: '2',
        name: 'Iced Latte',
        description: 'Espresso with cold milk and ice.',
        price: 180,
        image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?q=80&w=1974&auto=format&fit=crop',
        isPopular: true,
        isVeg: true,
    },
    {
        id: '11',
        categoryId: '2',
        name: 'Espresso',
        description: 'Strong, concentrated coffee shot.',
        price: 120,
        image: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?q=80&w=600&auto=format&fit=crop',
        isVeg: true,
    },
    {
        id: '12',
        categoryId: '2',
        name: 'Caramel Macchiato',
        description: 'Espresso with steamed milk and vanilla syrup, topped with caramel drizzle.',
        price: 210,
        image: 'https://images.unsplash.com/photo-1662047102608-a6f2e492411f?q=80&w=687&auto=format&fit=crop',
        isPopular: true,
        isVeg: true,
    },
    {
        id: '13',
        categoryId: '2',
        name: 'Mocha',
        description: 'Espresso with steamed milk and chocolate syrup.',
        price: 200,
        image: 'https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?q=80&w=600&auto=format&fit=crop',
        isVeg: true,
    },

    // Snacks
    {
        id: '3',
        categoryId: '3',
        name: 'Grilled Cheese Sandwich',
        description: 'Classic grilled cheese with herbs.',
        price: 220,
        image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?q=80&w=600&auto=format&fit=crop',
        isVeg: true,
    },
    {
        id: '4',
        categoryId: '3',
        name: 'Chicken Burger',
        description: 'Juicy chicken patty with fresh lettuce and mayo.',
        price: 290,
        image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=600&auto=format&fit=crop',
        isPopular: true,
        isVeg: false,
    },
    {
        id: '14',
        categoryId: '3',
        name: 'French Fries',
        description: 'Crispy salted golden fries.',
        price: 140,
        image: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?q=80&w=600&auto=format&fit=crop',
        isVeg: true,
    },
    {
        id: '15',
        categoryId: '3',
        name: 'Club Sandwich',
        description: 'Triple-decker sandwich with chicken, bacon, lettuce, and tomato.',
        price: 320,
        image: 'https://images.unsplash.com/photo-1553909489-cd47e3b4430f?q=80&w=600&auto=format&fit=crop',
        isVeg: false,
    },
    {
        id: '16',
        categoryId: '3',
        name: 'Pasta Alfredo',
        description: 'Creamy white sauce pasta with mushrooms.',
        price: 350,
        image: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?q=80&w=600&auto=format&fit=crop',
        isPopular: true,
        isVeg: true,
    },

    // Desserts
    {
        id: '5',
        categoryId: '4',
        name: 'Chocolate Brownie',
        description: 'Fudgy brownie with walnuts.',
        price: 120,
        image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?q=80&w=600&auto=format&fit=crop',
        isVeg: true,
    },
    {
        id: '17',
        categoryId: '4',
        name: 'Cheesecake',
        description: 'Classic New York style cheesecake slice.',
        price: 250,
        image: 'https://images.unsplash.com/photo-1524351199678-941a58a3df50?q=80&w=600&auto=format&fit=crop',
        isPopular: true,
        isVeg: true,
    },
    {
        id: '18',
        categoryId: '4',
        name: 'Tiramisu',
        description: 'Coffee-flavoured Italian dessert.',
        price: 280,
        image: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?q=80&w=600&auto=format&fit=crop',
        isVeg: true,
    },

    // Drinks
    {
        id: '19',
        categoryId: '5',
        name: 'Orange Juice',
        description: 'Freshly squeezed orange juice.',
        price: 160,
        image: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?q=80&w=600&auto=format&fit=crop',
        isVeg: true,
    },
    {
        id: '20',
        categoryId: '5',
        name: 'Blueberry Smoothie',
        description: 'Healthy smoothie made with fresh blueberries and yogurt.',
        price: 240,
        image: 'https://images.unsplash.com/photo-1532301634640-d623ab11bb22?q=80&w=688&auto=format&fit=crop',
        isPopular: true,
        isVeg: true,
    },
    {
        id: '21',
        categoryId: '5',
        name: 'Iced Tea',
        description: 'Refreshing lemon iced tea.',
        price: 130,
        image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?q=80&w=600&auto=format&fit=crop',
        isVeg: true,
    },
    // New Items
    {
        id: '22',
        categoryId: '2',
        name: 'Flat White',
        description: 'Espresso with microfoam.',
        price: 160,
        image: 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?q=80&w=600&auto=format&fit=crop',
        isVeg: true,
    },
    {
        id: '23',
        categoryId: '2',
        name: 'Americano',
        description: 'Espresso diluted with hot water.',
        price: 130,
        image: 'https://images.unsplash.com/photo-1551030173-122fabc48a75?q=80&w=600&auto=format&fit=crop',
        isVeg: true,
    },
    {
        id: '24',
        categoryId: '2',
        name: 'Affogato',
        description: 'Espresso poured over vanilla ice cream.',
        price: 190,
        image: 'https://images.unsplash.com/photo-1594261642231-64115167b572?q=80&w=600&auto=format&fit=crop',
        isVeg: true,
    },
    {
        id: '25',
        categoryId: '2',
        name: 'Cold Brew',
        description: 'Slow-steeped cold coffee served over ice.',
        price: 170,
        image: 'https://images.unsplash.com/photo-1517701604599-bb29b5c5090c?q=80&w=600&auto=format&fit=crop',
        isVeg: true,
    },
    {
        id: '26',
        categoryId: '3',
        name: 'Margherita Pizza',
        description: 'Classic cheese pizza with basil.',
        price: 350,
        image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=600&auto=format&fit=crop',
        isPopular: true,
        isVeg: true,
    },
    {
        id: '27',
        categoryId: '3',
        name: 'Pepperoni Pizza',
        description: 'Pizza topped with pepperoni slices.',
        price: 400,
        image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?q=80&w=600&auto=format&fit=crop',
        isVeg: false,
    },
    {
        id: '28',
        categoryId: '3',
        name: 'Garlic Bread',
        description: 'Toasted bread with garlic butter.',
        price: 150,
        image: 'https://images.unsplash.com/photo-1619535860434-7f086338b3d2?q=80&w=600&auto=format&fit=crop',
        isVeg: true,
    },
    {
        id: '29',
        categoryId: '3',
        name: 'Nachos Supreme',
        description: 'Nachos with cheese, salsa, and jalapenos.',
        price: 250,
        image: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?q=80&w=600&auto=format&fit=crop',
        isPopular: true,
        isVeg: true,
    },
    {
        id: '30',
        categoryId: '3',
        name: 'Veggie Wrap',
        description: 'Grilled vegetables wrapped in a tortilla.',
        price: 180,
        image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?q=80&w=600&auto=format&fit=crop',
        isVeg: true,
    },
    {
        id: '31',
        categoryId: '3',
        name: 'Chicken Wings',
        description: 'Spicy buffalo chicken wings.',
        price: 320,
        image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?q=80&w=600&auto=format&fit=crop',
        isPopular: true,
        isVeg: false,
    },
    {
        id: '32',
        categoryId: '4',
        name: 'Chocolate Donut',
        description: 'Glazed donut with chocolate sprinkles.',
        price: 90,
        image: 'https://images.unsplash.com/photo-1551024601-569d6f46319c?q=80&w=600&auto=format&fit=crop',
        isVeg: true,
    },
    {
        id: '33',
        categoryId: '4',
        name: 'Blueberry Muffin',
        description: 'Soft muffin filled with blueberries.',
        price: 110,
        image: 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?q=80&w=600&auto=format&fit=crop',
        isVeg: true,
    },
    {
        id: '34',
        categoryId: '4',
        name: 'Waffles',
        description: 'Belgian waffles with maple syrup.',
        price: 200,
        image: 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?q=80&w=600&auto=format&fit=crop',
        isPopular: true,
        isVeg: true,
    },
    {
        id: '35',
        categoryId: '4',
        name: 'Pancakes',
        description: 'Stack of fluffy pancakes with honey.',
        price: 190,
        image: 'https://images.unsplash.com/photo-1506084868230-bb9d95c24759?q=80&w=600&auto=format&fit=crop',
        isVeg: true,
    },
    {
        id: '36',
        categoryId: '4',
        name: 'Strawberry Ice Cream',
        description: 'Scoop of strawberry ice cream.',
        price: 100,
        image: 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?q=80&w=600&auto=format&fit=crop',
        isVeg: true,
    },
    {
        id: '37',
        categoryId: '5',
        name: 'Mango Smoothie',
        description: 'Thick mango smoothie with yogurt.',
        price: 180,
        image: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?q=80&w=600&auto=format&fit=crop',
        isPopular: true,
        isVeg: true,
    },
    {
        id: '38',
        categoryId: '5',
        name: 'Chocolate Shake',
        description: 'Rich chocolate milkshake.',
        price: 210,
        image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?q=80&w=600&auto=format&fit=crop',
        isVeg: true,
    },
    {
        id: '39',
        categoryId: '5',
        name: 'Lemonade',
        description: 'Sparkling lemon juice.',
        price: 120,
        image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=600&auto=format&fit=crop',
        isVeg: true,
    },
    {
        id: '40',
        categoryId: '5',
        name: 'Green Tea',
        description: 'Hot refreshing green tea.',
        price: 100,
        image: 'https://images.unsplash.com/photo-1627435601361-ec25f5b1d0e5?q=80&w=600&auto=format&fit=crop',
        isVeg: true,
    },
    {
        id: '41',
        categoryId: '5',
        name: 'Coconut Water',
        description: 'Fresh tender coconut water.',
        price: 80,
        image: 'https://images.unsplash.com/photo-1525385133512-2f346b384338?q=80&w=600&auto=format&fit=crop',
        isVeg: true,
    },
    {
        id: '42',
        categoryId: '2',
        name: 'Latte Macchiato',
        description: 'Layered coffee drink.',
        price: 190,
        image: 'https://images.unsplash.com/photo-1593456372693-8f250e6f0d14?q=80&w=600&auto=format&fit=crop',
        isVeg: true,
    }
];
